name: BUILD
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest    
    timeout-minutes: 5
    steps:
    - name: Pull zeebe
      run: docker pull camunda/zeebe:1.1.0
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build